### ISSUE TITLE
Version key required in manifest file

### ISSUE THREAD

**Issue by jmesberg** [thevoltagesource/myicomfort#4] opened 2021-03-05 17:56 UTC
Latest update of HA (2021.3.1) now throws warning "No 'version' key in the manifest file for custom integration 'myicomfort'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'myicomfort'".

Doesn't affect usage in any way at this time, but thought I'd let you know if you weren't already aware

**Comment by thevoltagesource** [comment] 2021-03-06 23:31
Thanks for letting me know.  Since this repository is for the backend API wrapper the integration relies on and the issue is with the actual HA integration, I am going to close this issue.  Someone else has also opened an issue on the HA integration. I will get it fixed soon.

**Closed as completed by thevoltagesource** 2021-03-06 23:31 UTC
